<h1><?= $this->title ?></h1>

<div id="myFirstReactPhpApp" v-cloak>
    <p v-show="showWait">Please wait</p>

    <p v-show="showEarlyError" class="ajaxError">{{ajaxError}}</p>

    <ul>
        <li v-for="task in tasks">
            {{task}}
        </li>
    </ul>

    <form @submit.prevent="addTask" v-show="tasks">
        <h1>Add</h1>
        <label>Task <input type="text" v-model="newtask"></label>
        <p v-show="ajaxError" class="ajaxError">{{ajaxError}}</p>
        <button type="submit" :disabled="disableForm">Save</button>
        <button type="button" @click="addTaskAsync" :disabled="disableForm">Save with asynchronous response</button>
    </form>
</div>